# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths-ignore:
    - '**/README.md'
    - '**/LICENSE'
    - 'visuals/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '**/README.md'
    - '**/LICENSE'
    - 'visuals/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

name: terraform-deploy

jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./infra
    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
         terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt
        
      - name: Terraform Plan
        run: terraform plan 
        
      - name: Preparation tests
        run: |
          terraform plan -out tfplan.tfplan
          terraform show -json tfplan.tfplan > tfplan.json

      - name: OPA tests
        id: opatests
        uses: agarciamiravet/confest-alex-github-action@main
        continue-on-error: true
        with:
          path: "infra/tfplan.json"
          policy: "opa-policies"
      
      #- name: Tests break build
      #  if: steps.opatests.outcome != 'success'
      #  run: exit 1
      
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ${{ github.workspace }}/src/terraform/tfplan.tfplan

      
  Deploy:
    needs: Build
    environment: production
    runs-on: 'ubuntu-latest'
    defaults:
        run:
          working-directory: ./infra
    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      
      - uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: ./infra

      - name: Terraform init
        run: terraform init
      
      - name: Terraform apply plan
        run: terraform apply --auto-approve tfplan.tfplan